sudo: false

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-1.22
    - ghc-7.10.1


before_install:
 - export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH


install:
 - travis_retry cabal update
 - cabal sandbox init --sandbox="`pwd`"/.cabal-sandbox
 - cabal install --only-dependencies --enable-tests


script:
 - cabal configure
 - cabal build
 - cabal install --enable-tests
 - ./tests/run-tests.sh
