name: Build Windows release

on:
  push:
    tags: '*'
    branches: 'release/*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Install stack
      shell: powershell
      run: |
        mkdir -p ~/stack-install
        cd ~/stack-install
        Invoke-WebRequest -OutFile ~/stack-install/stack.zip https://get.haskellstack.org/stable/windows-x86_64.zip
        7z x stack.zip stack.exe
        echo "::add-path::$HOME/stack-install"
    - uses: actions/cache@v1
      with:
        path: ~\AppData\Roaming\stack
        key: ${{ runner.os }}-stack
    - run: stack --version
    - run: stack setup
    - run: stack build --only-dependencies
    - run: stack install shake
    - name: Build
      run: stack runhaskell Shakefile.hs -- build
    - name: Copy binary
      shell: bash
      run: |
        mkdir -p dist
        stack install --local-bin-path=dist
        strip dist/elm-format.exe
        7z a -bb3 -tzip -mfb=258 -mpass=15 elm-format.zip "$(pwd)"/dist/elm-format.exe
    - shell: powershell
      run: Get-FileHash -Algorithm SHA1 dist/elm-format.exe
    - shell: powershell
      run: Get-FileHash -Algorithm SHA1 elm-format.zip
    - uses: actions/upload-artifact@v1
      with:
        name: elm-format.zip
        path: elm-format.zip
